### ISSUE TITLE
The app crashes when clicking on the "Cart" feature in landscape mode

### ISSUE THREAD

**Issue by ahyar92** [emanuelet/Trove#6]
#### Expected behavior
Supposedly, I can access the "Cart" feature in landscape mode.

#### Actual behavior
When I open one of the books, then turn the screen rotation into landscape mode, and then I click on the "Cart" feature the app suddenly crashes.

#### How to reproduce
1. Install and open the app
2. Do a book search
3. Then Click on one of the books
4. Change screen rotation to landscape mode, then click on feature or icon "Cart".

----
#### Environment
Tested on 3 devices:
<table>
<thead>
<tr><th>Device</th><th>Android Version</th>
</thead>
<tbody>
<tr><td>Xiaomi Redmi Note 4</td><td>Marshmallow, 6.0 mRA58K (DECA-CORE MAX 2,11GHz, RAM: 3 gb)</td>
<tr><td>Xiaomi Redmi 4X</td><td>Marshmallow, 6.0.1 mmb29m (CPU: Octa-core Max 1.9 GHz, RAM: 2 GB)</td>
<tr><td>Xiaomi Redmi Note 5A</td><td>Nougat, 7.1.0</td>

</tbody>
</table>

#### Recording Of The Bug
https://www.youtube.com/watch?v=lDxoWmkeVCE&feature=youtu.be

#### Logcat
```
05-30 23:42:45.567 25665 25665 E AndroidRuntime: Process: com.etapps.trovenla, PID: 25665
05-30 23:42:45.567 25665 25665 E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=null?q=+buy=true (has extras) }
05-30 23:42:45.567 25665 25665 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1809)
05-30 23:42:45.567 25665 25665 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1523)
05-30 23:42:45.567 25665 25665 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4018)
05-30 23:42:45.567 25665 25665 E AndroidRuntime: 	at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
05-30 23:42:45.567 25665 25665 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:67)
05-30 23:42:45.567 25665 25665 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:3979)
05-30 23:42:45.567 25665 25665 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:732)
05-30 23:42:45.567 25665 25665 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:4302)
05-30 23:42:45.567 25665 25665 E AndroidRuntime: 	at android.support.v4.content.ContextCompat.startActivity(ContextCompat.java:143)
05-30 23:42:45.567 25665 25665 E AndroidRuntime: 	at android.support.customtabs.CustomTabsIntent.launchUrl(CustomTabsIntent.java:262)
05-30 23:42:45.567 25665 25665 E AndroidRuntime: 	at com.etapps.trovenla.activities.BookDetailActivity.buyBook(BookDetailActivity.java:89)
05-30 23:42:45.567 25665 25665 E AndroidRuntime: 	at com.etapps.trovenla.activities.BookDetailActivity_ViewBinding$1.doClick(BookDetailActivity_ViewBinding.java:34)
05-30 23:42:45.567 25665 25665 E AndroidRuntime: 	at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
05-30 23:42:45.567 25665 25665 E AndroidRuntime: 	at android.view.View.performClick(View.java:5275)
05-30 23:42:45.567 25665 25665 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:21556)
05-30 23:42:45.567 25665 25665 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:815)
05-30 23:42:45.567 25665 25665 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:104)
05-30 23:42:45.567 25665 25665 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:207)
05-30 23:42:45.567 25665 25665 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5811)
05-30 23:42:45.567 25665 25665 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-30 23:42:45.567 25665 25665 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
05-30 23:42:45.567 25665 25665 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768)
```

**Comment by emanuelet** [comment]
Hi @ahyar92 thank you very much for taking the time to find this  bug. I'll look into it today

**Comment by emanuelet** [comment]
e39535c5ebf3a4c7e2134e876951b5ee90f70d7c fixes it
